// <auto-generated />
namespace TwilioRegistration.BusinessLogic.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class FailedLogins : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FailedLogins));
        
        string IMigrationMetadata.Id
        {
            get { return "201501281429400_FailedLogins"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
